
openapi: 3.0.1
info:
  title: Random Augmentation
  description:  |
    ## Upload some image then it will augment it.
    ---
    How to use:
      * Pick image what you want to augment
      * Excute and wait until the result shows up
    ---
  version: 1.0.0
  license:
    name: "MIT"
    url: ""
servers:
  - url: 'https://master-random-augmentation-wook-2.endpoint.ainize.ai/augment'

paths:
  /:
    post:
      tags:
      - Augmentor
      requestBody:
        required: true
        description: "Pick images and number"
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  description: Import Image Here
                  type: array
                  items:
                    type: string
                    format: binary
                number:
                  description: How many augmented images you need (each input)
                  type: integer
                  format: int32
                  minimum: 1
                  maximum: 20

      responses:
         '200':
            description: success
            content:
              application/zip:
                  schema:
                    type: string
                    format: binary

         '400':
            description: Bad request (Can not load images)
         '500':
            description: Server Side Error
